// Code generated by protoc-gen-go.
// source: pb.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	VerifySiteRequest
	VerifySiteResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VerifySiteRequest struct {
	SiteUrl string `protobuf:"bytes,1,opt,name=site_url,json=siteUrl" json:"site_url,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *VerifySiteRequest) Reset()                    { *m = VerifySiteRequest{} }
func (m *VerifySiteRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifySiteRequest) ProtoMessage()               {}
func (*VerifySiteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VerifySiteResponse struct {
	Found bool `protobuf:"varint,1,opt,name=found" json:"found,omitempty"`
}

func (m *VerifySiteResponse) Reset()                    { *m = VerifySiteResponse{} }
func (m *VerifySiteResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifySiteResponse) ProtoMessage()               {}
func (*VerifySiteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*VerifySiteRequest)(nil), "pb.VerifySiteRequest")
	proto.RegisterType((*VerifySiteResponse)(nil), "pb.VerifySiteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for CheckSite service

type CheckSiteClient interface {
	VerifySite(ctx context.Context, in *VerifySiteRequest, opts ...grpc.CallOption) (*VerifySiteResponse, error)
}

type checkSiteClient struct {
	cc *grpc.ClientConn
}

func NewCheckSiteClient(cc *grpc.ClientConn) CheckSiteClient {
	return &checkSiteClient{cc}
}

func (c *checkSiteClient) VerifySite(ctx context.Context, in *VerifySiteRequest, opts ...grpc.CallOption) (*VerifySiteResponse, error) {
	out := new(VerifySiteResponse)
	err := grpc.Invoke(ctx, "/pb.CheckSite/VerifySite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CheckSite service

type CheckSiteServer interface {
	VerifySite(context.Context, *VerifySiteRequest) (*VerifySiteResponse, error)
}

func RegisterCheckSiteServer(s *grpc.Server, srv CheckSiteServer) {
	s.RegisterService(&_CheckSite_serviceDesc, srv)
}

func _CheckSite_VerifySite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckSiteServer).VerifySite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CheckSite/VerifySite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckSiteServer).VerifySite(ctx, req.(*VerifySiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckSite_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CheckSite",
	HandlerType: (*CheckSiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifySite",
			Handler:    _CheckSite_VerifySite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x48, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x72, 0xe0, 0x12, 0x0c, 0x4b, 0x2d, 0xca,
	0x4c, 0xab, 0x0c, 0xce, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe4,
	0xe2, 0x28, 0xce, 0x2c, 0x49, 0x8d, 0x2f, 0x2d, 0xca, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x62, 0x07, 0xf1, 0x43, 0x8b, 0x72, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x98, 0xc0,
	0xa2, 0x20, 0xa6, 0x92, 0x16, 0x97, 0x10, 0xb2, 0x09, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0x22, 0x5c, 0xac, 0x69, 0xf9, 0xa5, 0x79, 0x29, 0x60, 0xfd, 0x1c, 0x41, 0x10, 0x8e, 0x91, 0x17,
	0x17, 0xa7, 0x73, 0x46, 0x6a, 0x72, 0x36, 0x48, 0xa9, 0x90, 0x2d, 0x17, 0x17, 0x42, 0xa3, 0x90,
	0xa8, 0x5e, 0x41, 0x92, 0x1e, 0x86, 0x53, 0xa4, 0xc4, 0xd0, 0x85, 0x21, 0xe6, 0x2b, 0x31, 0x24,
	0xb1, 0x81, 0x3d, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xa3, 0x82, 0xb2, 0xd0, 0x00,
	0x00, 0x00,
}
